### ISSUE TITLE
hosting librenms at a path not working

### ISSUE THREAD

**Issue by diepes** [librenms/helm-charts#40]
I am trying to deploy the helm chart to sit at a path under a base url.

e.g. https://myserver/librenms/

I deployed traefik ingressroute and middleware to stirp the /librenms

Currently when i connect to the url i get a 302 redirect to https://myserver/login

I tried removing the ingress middleware that strips /librenms, still getting the invalid redirectes to https://myserver/login

What is the correct settins to use a subpath ?
1. Should i have the ingress middle ware strip the path /librenms ?

In my values.yaml i have tried
```
librenms:
  extraEnvs:
    # https://docs.librenms.org/Support/Environment-Variables/#baseurl
    - name: APP_URL
      value: "https://myserver/librenms/"
    - name: LIBRENMS_BASE
      value: "/librenms"
    - name: TRUSTED_PROXIES
      value: "*"
```

I have also found examples such as
```
librenms:
  configuration: |
    $config['base_url']                 = 'https://myserver/librenms/';
```

Any suggestion on how to adjust the values.yaml ?
