### ISSUE TITLE
Help with values

### ISSUE THREAD

**Issue by samucabrave** [librenms/helm-charts#80]
Hello,
I'm using the helm_release resource from terraform to deploy Librenms to my EKS cluster, but the values that are default of the configmap override the values of the resource. Is there any option to disable the use of configmap and only keep the values ​​I defined? Another detail is that i use MariaDB on AWS as a database.

Bellow my librenms.tf

```
resource "helm_release" "librenms" {
  name       = "librenms"
  repository = "https://www.librenms.org/helm-charts"
  chart      = "librenms"
  version    = "4.0.3"
  namespace  = 

  create_namespace = true
  values = [<<EOF
frontend:
  replicas: 1
  service:
    type: ClusterIP
    port: 8000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

env:
  DB_HOST: 
  DB_PORT: "3306"
  DB_DATABASE:
  DB_USERNAME:
  DB_PASSWORD:

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: 
      paths:
        - path: /
          pathType: Prefix
  tls: []

pooler:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

snmp_scanner:
  enabled: true
  cron: "*/5 * * * *"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  
rrdcache:
  image:
    repository: crazymax/rrdcached
    tag: 1.8.0
  persistence:
    enabled: true
    journal:
    size: 1Gi
  rrdcache:
    size: 1Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
    livenessProbe:
      tcpSocket:
        port: 42217
      initialDelaySeconds: 15
      periodSeconds: 20
    envs:
    - name: TZ
      value: UTC
    - name: WRITE_JITTER
      value: '1800'
    - name: WRITE_TIMEOUT
      value: '1800'
EOF
  ]
}
```
